[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "file:./dev.db"
JWT_SECRET = "railway-prod-ecommerce-jwt-secret-2024-secure-deployment"
NEXTAUTH_SECRET = "railway-prod-nextauth-secret-2024-ecommerce-platform"
